apiVersion: apps/v1
kind: replicaset
metadata:
 name: myapp-replicaset
 label: 
  app: myapp
  type: front-end
spec: 
 template:
  metadata:
   name:
   labels:  
    app:
    type:
  spec:
   containers:
   - name:nginx-container
     image: nginx